accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("profile/", views.userProfile),
]

cms/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("company.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("kanban/", include("kanban.urls")),
]

company/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="home"),
]

kanban/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("addtask/", views.createTask, name="addtask"),
    path("updatetask/<pk>", views.updateTask, name="updatetask"),
    path("deletetask/<pk>", views.deleteTask, name="deletetask"),
]

accounts/models.py
from django.db import models

# Create your models here.

company/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Info(models.Model):
    name = models.CharField(max_length=30)
    address = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=30)
    code = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Info, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

kanban/models.py
from django.db import models
from django.contrib.auth.models import User
from company.models import Department

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=180)
    description = models.TextField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    ended_at = models.DateTimeField()

kanban/forms.py
from django import forms
from . import models


class AddTask(forms.Form):
    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    department = forms.ModelChoiceField(models.Department.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={"type": "time"}))

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def userProfile(request):
    context = {}
    return render(request, "accounts/profile.html", context)

company/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import models


@login_required
def index(request):
    allDeptObjs = models.Department.objects.all()
    context = {"allDeptObjs": allDeptObjs}
    return render(request, "company/dashboard.html", context)

kanban/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from . import forms, models
from datetime import datetime


@login_required
def createTask(request):
    if request.POST:
        addform = forms.AddTask(request.POST)
        if addform.is_valid():
            endTime = datetime.combine(
                addform.cleaned_data["date"], addform.cleaned_data["time"]
            )
            # print(endTime)
            newTask = models.Task(
                title=addform.cleaned_data["title"],
                description=addform.cleaned_data["description"],
                user=request.user,
                department=addform.cleaned_data["department"],
                ended_at=endTime,
            )
            newTask.save()
            print(newTask)
            return redirect("home")

    context = {
        "taskForm": forms.AddTask,
        "mode": "addtask",
        "actionName": "Add Task",
    }
    return render(request, "kanban/create_and_update_task.html", context)


@login_required
def updateTask(request, pk):
    taskObj = models.Task.objects.get(pk=pk)
    context = {
        "taskForm": forms.AddTask(
            initial={
                "title": taskObj.title,
                "description": taskObj.description,
                "department": taskObj.department,
                "date": taskObj.ended_at.date,
                "time": taskObj.ended_at.time,
            }
        ),
        "mode": "updatetask",
        "pk": pk,
        "actionName": "Update Task",
    }
    if request.POST:
        updatedform = forms.AddTask(request.POST)
        if updatedform.is_valid():
            endTime = datetime.combine(
                updatedform.cleaned_data["date"],
                updatedform.cleaned_data["time"],
            )
            taskObj.title = updatedform.cleaned_data["title"]
            taskObj.description = updatedform.cleaned_data["description"]
            taskObj.department = updatedform.cleaned_data["department"]
            taskObj.ended_at = endTime
            taskObj.save()
            return redirect("home")
    return render(request, "kanban/create_and_update_task.html", context)


@login_required
def deleteTask(request, pk):
    models.Task.objects.get(pk=pk).delete()
    context = {"taskForm": forms.AddTask}
    return redirect("home")

accounts/templates/accounts/profile.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Profile</title>
  </head>
  <body>
    <h1>Profile</h1>
    <ul>
      <li><a href="{% url 'home' %}">Dashboard</a></li>
    </ul>
  </body>
</html>

company/templates/company/dashboard.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Dashboard</title>
  </head>
  <body>
    <h1>Dashboard</h1>
    <p><a href="{% url 'logout' %}?next=/">Logout</a></p>
    {% for dept in allDeptObjs %}
      <h2>{{dept.name}}</h2>
      {% if request.user.username == dept.user.username  %}
	<ul>
	  <li><a href="{% url 'addtask' %}">Add Task</a></li>
	</ul>
      {% endif %}
      <table width="100%">
	{% for task in dept.task_set.all %}	  
	  <thead>
            <tr>
	      <th>Title</th>
	      <th>Creator</th>
	      <th>Description</th>
	      <th>Created Time</th>
	      <th>Updated Time</th>
	      <th>End Time</th>
	      <th></th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	    <tr>
	      <td>{{task.title}}</td>
	      <td>{{task.user}}</td>
	      <td>{{task.description}}</td>
	      <td>{{task.created_at}}</td>
	      <td>{{task.updated_at}}</td>
	      <td>{{task.ended_at}}</td>
	      {% if request.user.username == task.user.username  %}
		<td><a href="{% url 'updatetask' pk=task.id %}">Edit</a></td>
		<td><a href="{% url 'deletetask' pk=task.id %}">Delete</a></td>
	      {% endif %}
	    </tr>
	  </tbody>
	{% endfor %}
      </table>
    {% endfor %}
  </body>
</html>

kanban/templates/kanban/create_and_update_task.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Add Task</title>
  </head>
  <body>
    <form method="post" action="{% url mode pk %}">
      {% csrf_token %}
      {{ taskForm.as_p }}
      <input type="submit" value={{ actionName }}/>
    </form>
  </body>
</html>